version: v1.0.0

dsn: memory

serve:
    public:
        base_url: http://localhost:4433/
        cors:
            enabled: true
            allowed_origins:
                - http://localhost:3000
                - http://localhost:4000
            allowed_methods:
                - POST
                - GET
                - PUT
                - PATCH
                - DELETE
            allowed_headers:
                - Authorization
                - Cookie
                - Content-Type
            exposed_headers:
                - Content-Type
                - Set-Cookie
    admin:
        base_url: http://kratos:4434/

selfservice:
    default_browser_return_url: http://localhost:3000/
    allowed_return_urls:
        - http://localhost:3000

    methods:
        password:
            enabled: true
        oidc:
            enabled: true
            config:
                providers:
                    - id: gitlab
                      provider: gitlab
                      client_id: your-gitlab-client-id
                      client_secret: your-gitlab-client-secret
                      mapper_url: file:///etc/config/kratos/oidc.gitlab.jsonnet
                      scope:
                          - read_user
                          - openid
                          - profile
                          - email

    flows:
        error:
            ui_url: http://localhost:3000/error

        settings:
            ui_url: http://localhost:3000/settings
            privileged_session_max_age: 15m

        recovery:
            enabled: true
            ui_url: http://localhost:3000/recovery

        verification:
            enabled: true
            ui_url: http://localhost:3000/verification
            after:
                default_browser_return_url: http://localhost:3000/

        logout:
            after:
                default_browser_return_url: http://localhost:3000/login

        login:
            ui_url: http://localhost:3000/login
            lifespan: 10m

        registration:
            lifespan: 10m
            ui_url: http://localhost:3000/registration
            after:
                password:
                    hooks:
                        - hook: session
                        - hook: web_hook
                          config:
                              url: http://graphql-api:4000/webhook/user-created
                              method: POST
                              body: file:///etc/config/kratos/webhook.jsonnet

log:
    level: debug
    format: text
    leak_sensitive_values: true

identity:
    default_schema_id: default
    schemas:
        - id: default
          url: file:///etc/config/kratos/identity.schema.json

courier:
    smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
