{{- if .Values.external-secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: {{ include "pcf-chart.namespace" . }}
  labels:
    {{- include "pcf-chart.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.vaultBackendStore.server | quote }}
      path: {{ .Values.vaultBackendStore.path | quote }}
      version: {{ .Values.vaultBackendStore.version | quote }}
      namespace: {{ .Values.vaultBackendStore.namespace | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.vaultBackendStore.auth.kubernetes.mountPath | quote }}
          role: {{ .Values.vaultBackendStore.auth.kubernetes.role | quote }}
          serviceAccountRef:
            name: {{ .Values.vaultBackendStore.auth.kubernetes.serviceAccountRef.name | quote }}
{{- end }}