# [target.x86_64-unknown-linux-musl]
# # Configure for static linking
# rustflags = [
#     "-C", "target-feature=+crt-static",
#     "-C", "link-arg=-static"
# ]

# [build]
# # Use musl target by default in Docker
# target = "x86_64-unknown-linux-musl"
