{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.otelCollector.name }}-config
  namespace: {{ include "pcf-chart.namespace" . }}
  labels:
    {{- include "pcf-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:{{ .Values.otelCollector.ports.otlp-grpc }}
          http:
            endpoint: 0.0.0.0:{{ .Values.otelCollector.ports.otlp-http }}
      
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 10s
              static_configs:
                - targets: ['localhost:{{ .Values.otelCollector.ports.prometheus }}']

    processors:
      batch:
        timeout: 5s
        send_batch_size: 1024
      
      memory_limiter:
        check_interval: 1s
        limit_mib: 512
        spike_limit_mib: 128
      
      resource:
        attributes:
          - key: cluster.name
            value: pcf
            action: insert
          - key: namespace
            value: {{ include "pcf-chart.namespace" . }}
            action: insert

    exporters:
      prometheus:
        endpoint: "0.0.0.0:{{ .Values.otelCollector.ports.prometheus-exporter }}"
        
      otlp/tempo:
        endpoint: tempo:4317
        tls:
          insecure: true
      
      loki:
        endpoint: http://loki:3100/loki/api/v1/push
        
      debug:
        verbosity: detailed

    extensions:
      health_check:
        endpoint: 0.0.0.0:{{ .Values.otelCollector.ports.health-check }}
      
      zpages:
        endpoint: 0.0.0.0:{{ .Values.otelCollector.ports.zpages }}
      
      pprof:
        endpoint: 0.0.0.0:1777

    service:
      extensions: [health_check, zpages, pprof]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [otlp/tempo, debug]
        
        metrics:
          receivers: [otlp, prometheus]
          processors: [memory_limiter, batch, resource]
          exporters: [prometheus, debug]
        
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [loki, debug]
{{- end }}