# loki.yaml
auth_enabled: false

server:
    http_listen_port: 3100
    grpc_listen_port: 9096

common:
    path_prefix: /loki
    storage:
        filesystem:
            chunks_directory: /loki/chunks
            rules_directory: /loki/rules
    replication_factor: 1
    ring:
        instance_addr: 127.0.0.1
        kvstore:
            store: inmemory

schema_config:
    configs:
        - from: 2023-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
              prefix: index_
              period: 24h

# Configure storage limits and retention
limits_config:
    retention_period: 168h # 7 days
    ingestion_rate_mb: 16
    ingestion_burst_size_mb: 32
    max_streams_per_user: 0
    max_global_streams_per_user: 0
    allow_structured_metadata: false

# Compactor configuration for cleaning old data
compactor:
    working_directory: /loki/compactor
    compaction_interval: 10m
    retention_enabled: false
