# mimir.yaml
# Running in monolithic mode for simplicity
target: all

# Configure the server
server:
    http_listen_port: 9009
    grpc_listen_port: 9095
    log_level: info

# Configure blocks storage for long-term retention
common:
    storage:
        backend: filesystem
        filesystem:
            dir: /data/mimir-blocks

# Ingester configuration - handles incoming metrics
ingester:
    ring:
        instance_addr: 127.0.0.1
        kvstore:
            store: inmemory
        replication_factor: 1

# Store-gateway configuration - queries historical data
store_gateway:
    sharding_ring:
        replication_factor: 1

# Compactor configuration - optimizes storage
compactor:
    data_dir: /data/mimir-compactor
    sharding_ring:
        kvstore:
            store: inmemory

# Distributor configuration - receives metrics from Prometheus
distributor:
    ring:
        instance_addr: 127.0.0.1
        kvstore:
            store: inmemory

# Ruler configuration - handles alerting rules
ruler:
    enable_api: true
    rule_path: /data/rules

# Ruler storage configuration
ruler_storage:
    backend: filesystem
    filesystem:
        dir: /data/ruler-storage

# Limits configuration - controls resource usage
limits:
    # Accept metrics up to 1 hour in the past
    creation_grace_period: 1h
    # Keep metrics for 30 days
    compactor_blocks_retention_period: 720h
    # Disable forced HA tracker
    accept_ha_samples: false
    # Max number of labels per series
    max_label_names_per_series: 30