# otel-collector-config.yaml
extensions:
    health_check:
        endpoint: 0.0.0.0:13133
    pprof:
        endpoint: 0.0.0.0:1777
    zpages:
        endpoint: 0.0.0.0:55679

receivers:
    # Receive OTLP data from your applications
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
            http:
                endpoint: 0.0.0.0:4318

    # Collect metrics about the collector itself
    prometheus:
        config:
            scrape_configs:
                - job_name: "otel-collector"
                  scrape_interval: 10s
                  static_configs:
                      - targets: ["0.0.0.0:8888"]

processors:
    # Batch telemetry data to improve throughput
    batch:
        timeout: 1s
        send_batch_size: 1024

    # Add resource attributes to identify the environment
    resource:
        attributes:
            - key: deployment.environment
              value: "local"
              action: insert
            - key: service.namespace
              value: "default"
              action: insert

    # Memory limiter prevents OOM situations
    memory_limiter:
        check_interval: 1s
        limit_mib: 1024
        spike_limit_mib: 256

exporters:
    # Send traces to Tempo
    otlp/tempo:
        endpoint: tempo:4317
        tls:
            insecure: true

    # Send metrics to Prometheus (which will remote-write to Mimir)
    prometheusremotewrite:
        endpoint: "http://prometheus:9090/api/v1/write"
        tls:
            insecure: true

    # Send logs to Loki
    loki:
        endpoint: "http://loki:3100/loki/api/v1/push"

    # Debug exporter for troubleshooting
    debug:
        verbosity: detailed

service:
    pipelines:
        # Trace pipeline configuration
        traces:
            receivers: [otlp]
            processors: [memory_limiter, batch, resource]
            exporters: [otlp/tempo]

        # Metrics pipeline configuration
        metrics:
            receivers: [otlp, prometheus]
            processors: [memory_limiter, batch, resource]
            exporters: [prometheusremotewrite]

        # Logs pipeline configuration
        logs:
            receivers: [otlp]
            processors: [memory_limiter, batch, resource]
            exporters: [loki]

    # Enable extensions for health checks and debugging
    extensions: [health_check, pprof, zpages]
