# prometheus.yml
global:
    scrape_interval: 15s
    evaluation_interval: 15s

# Remote write configuration for Mimir
remote_write:
    - url: http://mimir:9009/api/v1/push
      send_exemplars: true
      queue_config:
          capacity: 10000
          max_shards: 200
          max_samples_per_send: 5000

# Scrape configurations
scrape_configs:
    # Scrape metrics from the OTEL collector
    - job_name: "otel-collector"
      static_configs:
          - targets: ["otel-collector:8889"]
      metric_relabel_configs:
          # Add environment label to all metrics
          - source_labels: [__address__]
            target_label: environment
            replacement: "local"
