# tempo.yaml
server:
    http_listen_port: 3200

distributor:
    receivers:
        otlp:
            protocols:
                grpc:
                    endpoint: 0.0.0.0:4317

ingester:
    max_block_duration: 5m

compactor:
    compaction:
        block_retention: 24h

storage:
    trace:
        backend: local
        local:
            path: /var/tempo/blocks
        wal:
            path: /var/tempo/wal

querier:
    frontend_worker:
        frontend_address: 127.0.0.1:9095
