# Default Configuration Example for Phase 1
# This file demonstrates the configuration structure

[server]
port = 8080
bind = "0.0.0.0"
shutdown_timeout = 30  # seconds

[logging]
level = "info"
format = "json"  # "json" for production, "pretty" for development

[health]
liveness_path = "/health"
readiness_path = "/health/ready"
startup_timeout_seconds = 300
startup_check_interval_seconds = 5

# Environment variable overrides:
# APP_SERVER__PORT=9090
# APP_LOGGING__LEVEL=debug
# APP_LOGGING__FORMAT=pretty

# CLI argument overrides (highest priority):
# --port 3000
# --debug (sets log level to debug)