clean:
    pkill -f "pcf-api"
    pkill -f "surreal"
    rm -rf target

build:
    cargo build --release

build-all: build build-docker

build-docker:
    docker build -t arustydev/pcf-api -f build/Dockerfile .

test:
    cargo test
